baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My projects'
theme = 'ananke'

[params]
  description = 'A personal blog'
  # Featured image shown on the home page
  # featured_image = '/images/gohugo-default-sample-hero-image.jpg'

[taxonomies]
  tag = 'tags'
  category = 'categories'
