baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My projects'
theme = 'ananke'

[markup.tableOfContents]
  startLevel = 1
  endLevel = 4
  ordered = false

[params]
  description = 'A personal blog'
  featured_image_class = "cover bg-center"

[taxonomies]
  tag = 'tags'
  category = 'categories'
